name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

          # We build the app on base-href flag (/web/index.html)
      - name: Build Web Application
        run: flutter build web --base-href "/${{ github.event.repository.name }}/" --release

        # We copy the generated content to 404.html to handle page reloading.background: 
      - name: Create 404.html for Pages routing
        run: cp build/web/index.html build/web/404.html

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5